name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Generate Highlight.js themes
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          cd $GITHUB_WORKSPACE

          git clone "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" hljs -b highlight.js

          cd hljs

          git rm -rf *.css || true
          git rm -rf *.json || true

          mv ../themes/highlight.js/* ./

          git add .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Built highlight.js themes for ${GITHUB_SHA}" || true
          git push origin highlight.js

      - name: Generate Pygments themes
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          cd $GITHUB_WORKSPACE

          git clone "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" pygments -b pygments

          cd pygments

          git rm -rf *.css || true
          git rm -rf *.json || true

          mv ../themes/pygments/* ./

          git add .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Built pygments themes for ${GITHUB_SHA}" || true
          git push origin pygments

      - name: Checkout vim Repo
        uses: actions/checkout@v2
        with:
          repository: 'EpokTarren/themes.vim'
          token: ${{ secrets.PR_PAT }}
          path: 'themes.vim'

      - name: Move files to VIM repo
        run: |
          cd $GITHUB_WORKSPACE
          cd "themes.vim"
          git rm *.vim || true
          mv ../themes/vim/* ./

      - name: VIM PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PR_PAT }}
          path: 'themes.vim'
          commit-message: Update to new version
          branch: auto-update
          title: 'New release'
          body: |
            Automatically generated new version of vim theme.

            PR generated from https://github.com/EpokTarren/themes/blob/master/.github/workflows/publish.yml
